# Generated by Django 4.1.5 on 2023-01-05 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.PositiveIntegerField(unique=True)),
                ('item_type', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('url', models.URLField()),
            ],
        ),
    ]
