# Generated by Django 4.1.5 on 2023-01-06 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='body',
        ),
        migrations.RemoveField(
            model_name='news',
            name='item_id',
        ),
        migrations.RemoveField(
            model_name='news',
            name='item_type',
        ),
        migrations.AddField(
            model_name='news',
            name='api_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='items.news'),
        ),
        migrations.AddField(
            model_name='news',
            name='type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
